version: "3"

services:

  backend:
    build: .
    networks:
      prox:
        ipv4_address: 172.18.0.3

  frontend: 
    build: ./frontend/
    depends_on:
      - backend
    networks:
      prox:
        ipv4_address: 172.18.0.4

  reveresefoxy:
    build: ./reverseproxy/
    networks:  
      prox:
        ipv4_address: 172.18.0.2
    ports:
      - 8080:8080
      - 80:80

networks:
  prox:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16